name: Build release

on:
  push:
    tags:
      - 'v*'


jobs:
  build:
    name: Build with google cloud
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: ${{ secrets.GCP_BUILD_PROJECT_ID }}
    permissions:
      contents: 'read'
      id-token: 'write'

    # Extract version tags from tag
    steps:
    - name: Setup variables
      id: variables
      run: |-
        TAG_NAME=${GITHUB_REF/refs\/tags\//}
        FULL_V_TAG=$(echo $TAG_NAME | sed -r 's/^v(.+)/\1/')
        MINOR_V_TAG=$(echo $FULL_V_TAG | sed -r -e 's/.*-(\w+)/\1/' -e 's/(^[0-9]+\.[0-9]+).*/\1/')
        MAJOR_V_TAG=$(echo $MINOR_V_TAG | sed -r -e 's/(^[a-z]+).*/\1/' -e 's/(^[0-9]+).*/\1/')

        echo "full_version_tag=$FULL_V_TAG" >> $GITHUB_OUTPUT
        echo "minor_version_tag=$MINOR_V_TAG" >> $GITHUB_OUTPUT
        echo "major_version_tag=$MAJOR_V_TAG" >> $GITHUB_OUTPUT

    - name: Checkout
      uses: actions/checkout@v3

    - id: auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GCP_BUILD_SERVICE_ACCOUNT_KEY }}'

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_BUILD_PROJECT_ID }}

    # Build and push image to Google Container Registry
    - name: Build
      run: |-
        gcloud builds submit \
          --quiet \
          --tag "eu.gcr.io/$PROJECT_ID/hub/functions:$GITHUB_SHA"

    - name: Tag image
      run: |-
        gcloud container images add-tag --quiet \
          "eu.gcr.io/$PROJECT_ID/hub/functions:$GITHUB_SHA" \
          "eu.gcr.io/$PROJECT_ID/hub/functions:${{ steps.variables.outputs.full_version_tag }}"

        gcloud container images add-tag --quiet \
          "eu.gcr.io/$PROJECT_ID/hub/functions:$GITHUB_SHA" \
          "eu.gcr.io/$PROJECT_ID/hub/functions:${{ steps.variables.outputs.minor_version_tag }}"

        gcloud container images add-tag --quiet \
          "eu.gcr.io/$PROJECT_ID/hub/functions:$GITHUB_SHA" \
          "eu.gcr.io/$PROJECT_ID/hub/functions:${{ steps.variables.outputs.major_version_tag }}"
