name: Build release

on:
  push:
    tags:
      - 'v*'


jobs:
  build:
    name: Build with google cloud
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: ${{ secrets.GCP_BUILD_PROJECT_ID }}

    # Extract version tags from tag
    steps:
    - name: Setup variables
      id: variables
      run: |
        TAG_NAME=${GITHUB_REF/refs\/tags\//}
        FULL_V_TAG=$(echo $TAG_NAME | sed -r 's/^v(.+)/\1/')
        MINOR_V_TAG=$(echo $FULL_V_TAG | sed -r -e 's/.*-(\w+)/\1/' -e 's/(^[0-9]+\.[0-9]+).*/\1/')
        MAJOR_V_TAG=$(echo $MINOR_V_TAG | sed -r -e 's/(^[a-z]+).*/\1/' -e 's/(^[0-9]+).*/\1/')

        echo ::set-output name=full_version_tag::$FULL_V_TAG
        echo ::set-output name=minor_version_tag::$MINOR_V_TAG
        echo ::set-output name=major_version_tag::$MAJOR_V_TAG

    - name: Checkout
      uses: actions/checkout@v2

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@v0
      with:
        version: '286.0.0'
        project_id: ${{ secrets.GCP_BUILD_PROJECT_ID }}
        service_account_email: ${{ secrets.GCP_BUILD_SERVICE_ACCOUNT_EMAIL }}
        service_account_key: ${{ secrets.GCP_BUILD_SERVICE_ACCOUNT_KEY }}

    # Build and push image to Google Container Registry
    - name: Build
      run: |-
        gcloud builds submit \
          --quiet \
          --tag "eu.gcr.io/$PROJECT_ID/hub/functions:$GITHUB_SHA"

    - name: Tag image
      run: |-
        gcloud container images add-tag --quiet \
          "eu.gcr.io/$PROJECT_ID/hub/functions:$GITHUB_SHA" \
          "eu.gcr.io/$PROJECT_ID/hub/functions:${{ steps.variables.outputs.full_version_tag }}"

        gcloud container images add-tag --quiet \
          "eu.gcr.io/$PROJECT_ID/hub/functions:$GITHUB_SHA" \
          "eu.gcr.io/$PROJECT_ID/hub/functions:${{ steps.variables.outputs.minor_version_tag }}"

        gcloud container images add-tag --quiet \
          "eu.gcr.io/$PROJECT_ID/hub/functions:$GITHUB_SHA" \
          "eu.gcr.io/$PROJECT_ID/hub/functions:${{ steps.variables.outputs.major_version_tag }}"
